require "main.options"
require "main.keymaps"
require "main.plugins"
require "main.colorscheme"
require "main.configs.nvim-cmp"
require "main.lsp"
require "main.configs.telescope"
require "main.configs.treesitter"
require "main.configs.lualine"
require "main.configs.dashboard"
require "main.configs.autopairs"
require "main.configs.bufferline"
require "main.configs.go-nvim"
require "main.configs.nvim-transparent"

